#!/bin/bash

if [ -z $1 ]; then
	echo 1>&2 "Usage: $0 [soup]"
  exit 127
fi

	url=http://${1}.soup.io/rss/

	wget -qO - $url | grep -o '<enclosure [^>]*>' | grep -o 'http://[^\"]*'  | sed 's/_[0-9][0-9][0-9]\././' | sed 's/\.jpeg/.jpg/'

exit 0
