#!/bin/bash

if [ -z $1 ]; then
    echo 1>&2 "Usage: $0 [feed url]"
    exit 127
fi

wget -qO - $1 | grep -o '<enclosure [^>]*>' | grep -o 'http://[^\"]*'  | sed 's/_[0-9][0-9][0-9]\././' | sed 's/\.jpeg/.jpg/'

exit 0
