#!/bin/bash

# Kein Kommentar #

## Variablen
# Zielordner der Bilder
ordner=$HOME/bilder
# Namen der soups
suppe=(fnordpad sixtus fotochaoten kochchaoten gnd)
# Name und Ort des parsers
feedparser=$HOME/feedparser
webparser=$HOME/webparser

# Bilderordner anlegen, falls er nicht existiert
if [ ! -d "$ordner" ] ; then
  mkdir -p $ordner
fi


for name in ${suppe[@]}; do

	# die rss Feeds parsen
	wget -qc -P $ordner `$feedparser $name`

	# die Reposts von der Seite holen
	wget -qc -P $ordner `$webparser $name`
	
done

exit 0
