#!/bin/bash

if [ -z $1 ]; then
  echo 1>&2 "Usage: $0 [soup]"
  exit 127
fi

if [ -z $2 ]; then
	pages=5
else
	pages=$2
fi

for ((i=0; i<pages; i++)); do

	#Adresse zusammenstückeln
	url=http://${1}.soup.io/${since}	

	wget -qO - $url | grep -o 'http://[0-9a-z].asset.soup.io/asset/[^0000][^\"]*' | grep -wv square* | sed 's/_[0-9][0-9][0-9]\././' | sed 's/_[0-9][0-9]\././' | sed 's/\.jpeg/.jpg/'

	#Umblättern
	since=`wget -qO - $url | grep -w 'SOUP.Endless.next_url' | grep -o "since[^\']*" | awk '{ sub(/\?mode\=own/, ""); print }'`

done 

exit 0
