#!/bin/bash
xrandr --output HDMI-0 --mode "1280x1024" &
setterm -blank 0 -powerdown 0 &
xset s off &
xset -dpms &
xset s noblank &
unclutter -idle 3 -root &
uzbl-browser -u file:///home/castor/frame.html -g 1024x768
