#!/bin/bash
xrandr --output VGA1 --mode 1280x1024 &
xset s off -display :0 &
xset -dpms -display :0 &
xset s noblank -display :0 &
unclutter -idle 3 -root &
xsetroot -solid darkgrey &
surf file:///srv/www/fnordpad/etc/frame.html &
exec dwm
